apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: oas
      image: gcr.io/rpa-devops/oas
      tty: true
      env:
        - name: GRADLE_USER_HOME
          value: .gradle
